source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HOBUtility', :exclusive => true do
  pod "HOBUtility", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "HOBUtility", :path => "../"

  pod 'Specta', '~> 1.0.0'
  pod 'Expecta', '~> 1.0.0'
end
